# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"kitty" = "ï„ "
"termite" = "ï„ "
"code-oss" = "ï„ "

"github" = "ï„“"
"rust" = "î¨"
"discord" = "ï‡¿"
"vesktop" = "ï‡¿"
"signal" = "ó°¿Œ"


# Games Things
"steam" = "ï†·"
"wine" = "î¶®"
"bh.x86_64" = "ï€­"

"google" = "ï† "
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"vivaldi" = "ï’ˆ"

"file manager" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ó°ˆ™"
"obsidian" = "ó°ˆ™"
"libreoffice" = "ó°†"

"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"

"calculator" = "ï‡¬"
"transmission" = "ï€™"
"qbittorrent" = "ï€™"

"feh" = "ï€"
"gimp" = "ï€"
"videostream" = "ï”¬"
"mpv" = "ï”¬"
"plex" = "ó°šº"
"syncplay" = "ó°šº"
"music" = "ï€"
"cider" = "ï€"
"pavucontrol" = "ó±„¡"


"disk usage" = "ï‡"
".pdf" = "ï‡"
"mupdf" = "ï‡"
"okular" = "ï‡"



[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = true
separator = ": "
